project_name: ai-fusion-bal-scheduler
model:
  load-outputs-and-parse: 
    command: >-
      [](make download file=<s3path>;) cd src/; python parse_and_save_outputs.py -d ../<s3path> -o ../<s3path>/parsed.h5; cd ../; make upload file=<s3path>/parsed.h5;
    gpu_count: 0
    memory: 30
    cpu_count: 2
    ephemeral_storage: 100
  load-inputs-and-parse: 
    command: >-
      [](make download file=<s3path>;) cd src/; python parse_input_candidates.py -f ../<s3path> -0 ../<s3path>/expanded/; cd ../; make upload file=<s3path>/expanded/;
    gpu_count: 0
    memory: 30
    cpu_count: 2
    ephemeral_storage: 100
  bal-from-scratch: # download TGLF-SINN checkpoint
    command: >-
      [](make download file=tglf_sumf_data_full_madcut_filter/train_filtered/tglfnn_DB_sat2_em_azf-1_RLNS_12_+1_azf-1_processed.h5;) python train.py; make upload file=;
    gpu_count: 1
    memory: 30
    cpu_count: 4
    ephemeral_storage: 200
  bal-from-checkpoint: # download TGLF-SINN checkpoint AND last CGYRO-NN checkpoint
    command: >-
      [](make download file=tglf_sumf_data_full_madcut_filter/train_filtered/tglfnn_DB_sat2_em_azf-1_RLNS_12_+1_azf-1_processed.h5;) python train.py; make upload file=;
    gpu_count: 1
    memory: 30
    cpu_count: 4
    ephemeral_storage: 200